### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by Timothyrichpt** [VisualPT/visualPT_site#12]
This page has been blank for almost 3 weeks now.

We need a text editor that I can use to add content. 

We've got people looking for us and searching at our content and finding this 404 error. This makes us look unprofessional.

![image](https://github.com/VisualPT/visualPT_site/assets/124405841/e128ada0-7972-44ac-9ad3-a1cf263a86f6)

![image](https://github.com/VisualPT/visualPT_site/assets/124405841/adf90bc0-c933-4f81-9704-733cf616e5fa)

**Comment by charlieforward9** [comment]
I fixed this, sorry about the wait.
